name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t mediacms/mediacms:latest .
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose-named-volumes.yaml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs mediacms_web_1
    # - name: Run test suite
    #   run: docker exec backend pytest --skip-auth