# name: Django CI

# on: [push, pull_request]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.6, 3.7, 3.8]
#     services:
#       postgres:
#         image: postgres:10.8
#         env:
#           POSTGRES_USER: mediacms
#           POSTGRES_PASSWORD: mediacms
#           POSTGRES_DB: mediacms
#         ports:
#           - 5432:5432
#         # needed because the postgres container does not provide a healthcheck
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: psycopg2 prerequisites
#       run: sudo apt-get install libpq-dev supervisor nginx ffmpeg imagemagick procps
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run migrations
#       run: |
#         pwd
#         mkdir logs
#         touch logs/debug.log
#         python manage.py migrate
#         python manage.py loaddata fixtures/encoding_profiles.json
#         python manage.py loaddata fixtures/categories.json
#         python manage.py collectstatic --noinput
#     # - name: Run Django Tests
#     #   run: |
#     #     python manage.py test